### PR TITLE
Update old ScalarDL cli commands with new subcommands for v3.9.0

### PR DESCRIPTION
**Pull request by monkey-mas**
## Description

Since the new ScalarDL cli subcommands are available from `v3.9.0`, we'll update the corresponding old commands.

## Related issues and/or PRs

N/A

## Changes made

- `scalardl` is used as the top-level executable command.
- The old commands are used as subcommands, e.g., `scalardl register-function`.

To update the documentation properly, we replaced `/client/bin/${COMMAND}` with `/client/bin/scalardl ${COMMAND}` by executing the following command on Mac terminal.

```terminal
git grep -Il '.' | xargs -n 10 sed -i '' "s/client\/bin\//client\/bin\/scalardl /g"
```
## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by choplin — APPROVED** [review]
LGTM!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by josh-wong — APPROVED** [review]
LGTM! Thank you!🙇‍♂️

**Review by jnmt — APPROVED** [review]
LGTM! Thank you for the update.

**Pull request merged**
