### PR TITLE
Add an implementation document

### PR DESCRIPTION
**Pull request by feeblefakie**
It's mostly a copy of the blog post...

### CODE REVIEW

**Review by jnmt — COMMENTED** [review]
Thank you! The contents itself is looking good to me. Just one question, are there any links to this page?

**Review by supl — APPROVED** [review]
LGTM.
Thank you!

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Comment by kota2and3kan** [comment]
@jnmt 

>  Just one question, are there any links to this page?

I think the link to this page is existing in the new Getting Started Guide that is updating in the following PR.
https://github.com/scalar-labs/scalardl/pull/26
https://github.com/scalar-labs/scalardl/blob/update-getting-started/docs/getting-started.md?plain=1#L11

However, it may be better to add the link to this page in the following index too.
https://github.com/scalar-labs/scalardl/blob/master/docs/index.md

**Review by jnmt — APPROVED** [review]
@kota2and3kan Thank you! Now, I found it.
@feeblefakie I think it's enough since we can reach this page at least. Thank you!

**Comment by feeblefakie** [comment]
@jnmt @kota2and3kan Thank you for pointing it out! Let me adjust the index pages (index.md and README.md) later.

**Pull request merged**
