### PR TITLE
Update Javadoc

### PR DESCRIPTION
**Pull request by jnmt**
## Description

This PR updates Javadoc for recent ScalarDL releases, i.e., v3.8.1, v3.9.0, and v3.9.1. We have a plan to migrate to the hosting in javadoc.io, the same as ScalarDB, but we should have the docs for those versions before completing the migration.

I created docs with the following steps.

```sh
cd scalar
git checkout v3.9.1
./gradlew javadoc
mv docs/javadoc ../scalardl/docs/javadoc/3.9.1
# repeated for other versions
```

## Related issues and/or PRs

N/A

## Changes made

- Add Javadoc for v3.8.1, v3.9.0, and v3.9.1
- Update index

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes.
- [ ] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [ ] Tests (unit, integration, etc.) have been added for the changes.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

### CODE REVIEW

**Review by kota2and3kan — APPROVED** [review]
I only checked it roughly, but LTGM! Thank you!

**Review by KodaiD — APPROVED** [review]
LGTM. Thank you!

**Review by feeblefakie — COMMENTED** [review]
I think we can just add the 3.9.0 docs since patch version upgrades should not change the APIs.
What do you think?

**Comment by jnmt** [comment]
> I think we can just add the 3.9.0 docs since patch version upgrades should not change the APIs. What do you think?

@feeblefakie Thanks for the comment. As discussed, I removed 3.8.1 and 3.9.1 to make the list consistent with others although some users might want to see the doc with their used versions. All versions will be provided once we move to javadoc.io.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
