### PR TITLE
Update the compatibility matrix

### PR DESCRIPTION
**Pull request by feeblefakie**
## Description

This PR updates the compatibility matrix since it was pretty stale.

## Related issues and/or PRs

N/A
## Changes made

- Updated the compatibility matrix

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes.
- [ ] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [ ] Tests (unit, integration, etc.) have been added for the changes.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A
## Release notes

Updated the compatibility matrix

### CODE REVIEW

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Review by josh-wong — APPROVED** [review]
LGTM! Thank you!🙇‍♂️

**Review by jnmt — APPROVED** [review]
LGTM! Thank you!

**Comment by josh-wong** [comment]
Sorry, I just realized that this change should be made in the [scalar-labs/docs-internal-scalardl](https://github.com/scalar-labs/docs-internal-scalardl) repository.

Since I think we're close to merging this PR, I'll copy the contents to the branches in [scalar-labs/docs-internal-scalardl](https://github.com/scalar-labs/docs-internal-scalardl) after this PR has been merged.

**Pull request merged**
