### PR TITLE
Add notice about the relocation of docs

### PR DESCRIPTION
**Pull request by josh-wong**
## Description

This PR adds a cautionary notice to the top of docs in the `docs` folder. Since those docs should now be updated in the [scalar-labs/docs-internal](https://github.com/scalar-labs/docs-internal) repository, the cautionary notice that I've added here is to provide guidance for those who may not know where to update the docs.

> [!NOTE]
>
> If the cautionary notice that I've added in this PR looks OK, I'll submit a similar PR that includes adding the same cautionary notice to docs in other ScalarDL-related repositories.

## Related issues and/or PRs

> If this PR addresses or references any issues and/or other PRs, list them here.

## Changes made

- Added a cautionary notice to the top of each doc in the `docs` folder, stating that the doc should be updated in the [scalar-labs/docs-internal](https://github.com/scalar-labs/docs-internal) repository.

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

The `docs` folder in this repository can be deleted after we have moved all product docs to the [scalar-labs/docs-internal](https://github.com/scalar-labs/docs-internal) repository and confirmed that the migration was a success.

## Release notes

N/A

### CODE REVIEW

**Review by supl — APPROVED** [review]
LGTM.
Thank you, Josh 🙇 

Sorry, I might have missed the discussion.
Do we plan to remove the `docs` folder in each repository in the future? (To not leave outdated materials)

**Comment by josh-wong** [comment]
> Sorry, I might have missed the discussion.
> Do we plan to remove the `docs` folder in each repository in the future? (To not leave outdated materials)

@supl Yes, that's correct. After we have confirmed that all docs are in the private, centralized docs repository and that we don't encounter any problems in that centralized repository, we will remove the `docs` folder.

**Review by jnmt — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
